[tool.poetry]
name = "pySigma-validators-sigmahq"
version = "0.5.2"
description = "pySigma SigmaHQ validators"
authors = ["Fran√ßois Hubaut <frack113@users.noreply.github.com>"]
license = "LGPL-2.1-only"
readme = "README.md"
repository = "https://github.com/frack113/pySigma_validators_sigmaHQ"
packages = [
    { include = "sigma" }
]

[tool.poetry.dependencies]
python = "^3.8"
pysigma = "^0.11"

[tool.poetry.group.dev.dependencies]
black = "^24.1"
coverage = "^7.4"
defusedxml = "^0.7"
pytest = "^8.0"
pytest-cov = "^4.1"

[build-system]
requires = ["poetry-core>=1.8.1"]
build-backend = "poetry.core.masonry.api"
